### ISSUE TITLE
Comments for rust integer parsing

### ISSUE THREAD

**Issue by Lonami** [rust-malaysia/rust-malaysia.github.io#4]
Not sure if this is the right place to leave "comments" but in https://rust-malaysia.github.io/code/2020/07/11/faster-integer-parsing.html it is said several times "ms" when it's meant "ns" (dropping some ms off ns timings would go back in time :P).

**Comment by pickfire** [comment]
Haha, @Lonami you found the article! :D I didn't notice it when writing the post, ms and ns somehow seemed not so different for me. Fixed it. Hope you enjoyed it. ^^
